### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by mengya1** [luojiaaoo/python-can-zlg#1]
你好作者，想咨询一个问题，如何对bus实例化：
我用Canoe的话是这样写的：
import can
from can.interfaces.vector import VectorBus
bus=can.interfaces.vector.canlib.VectorBus(app_name='pycan',channel=0,
                                           bitrate=500000,data_bitrate=2000000,
                                           fd=False)
你的zlg的我不清楚怎样搞，能给个例子吗，Thanks♪(･ω･)ﾉ

**Comment by luojiaaoo** [comment]
### My Example:

```
import can
can_filters = [dict(is_extended=1, filter_start=UDS_PhysicalRequestID, filter_end=UDS_PhysicalRequestID),]
bus = can.interface.Bus(bustype='zlg', channel=self.channel, dev_type=dev_type, fd=self.fd_bus, bitrate=bitrate,
                                 data_bitrate=data_baudrate, receive_own_messages=True, can_filters=can_filters)
```

**Comment by mengya1** [comment]
能给个类似下面这种例子嘛：
import can
from can.interfaces.zlg import ZlgUsbCanBus

bus = can.interfaces.zlg.ZlgUsbCanBus(
    channel=0,fd=False,bitrate=500000,data_bitrate=2000000,dev_type=39,
)

msg = can.Message(arbitration_id=0x111,
                  data=[0x02, 0x10, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00],
                  is_extended_id=False, )

bus.send(msg)

rec=bus.recv()
print(rec)
bus.shutdown()

**Comment by luojiaaoo** [comment]
import can
bus = can.interface.Bus(bustype='zlg', channel=0, dev_type=39, fd=False,bitrate=500000)
msg = can.Message(arbitration_id=0x111,
data=[0x02, 0x10, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00],
is_extended_id=False, )
bus.send(msg)
rec=bus.recv()
print(rec)
bus.shutdown()
